name: MILA Exec (Reusable)

on:
  workflow_call:
    secrets:
      OPENAI_API_KEY:   { required: true }
      VERCEL_TOKEN:     { required: false }
      VERCEL_ORG_ID:    { required: false }
      VERCEL_PROJECT_ID: { required: false }

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Checkout Mila-Ops
        uses: actions/checkout@v4
        with:
          repository: RareCurveLabs/Mila-Ops
          path: .mila-ops
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Install caller deps (best-effort)
        run: pnpm i || true

      - name: Ensure gh is available
        run: |
          type -p gh || (sudo apt-get update && sudo apt-get install -y gh)

      - name: Configure Git identity
        run: |
          git config --global user.name  "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run MILA runner from Mila-Ops
        env:
          OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}
          # Use the built-in token – do NOT declare it under workflow_call
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN:         ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN:     ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID:    ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          MILA_AUTONOMY:    ${{ vars.MILA_AUTONOMY || 'L2' }}
        run: node .mila-ops/scripts/mila-runner.cjs
