name: MILA Exec

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'mila:go')) ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/go'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g pnpm
      - run: pnpm i || true
      - name: Run MILA
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Built-in token provided by Actions—no need to create manually
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          MILA_AUTONOMY: ${{ vars.MILA_AUTONOMY || 'L2' }}
        run: node scripts/mila-runner.cjs